#include <catch2/catch_test_macros.hpp>

#include <cstdlib>
#include <fstream>

#include <boost/filesystem.hpp>
#include <nlohmann/json.hpp>

#include "libslic3r/miniz_extension.hpp"
#include "slic3r/Utils/BambuLanClient.hpp"

using namespace Slic3r;
namespace fs = boost::filesystem;

TEST_CASE("Bambu MQTT packets", "[BambuLan]")
{
    SECTION("connect") {
        const std::string p = BambuMqtt::connect_packet("tisma_1", "bblp", "12345678", 60);
        // Fixed header CONNECT, then "MQTT", level 4, flags user+password+clean session, keep alive 60.
        REQUIRE(uint8_t(p[0]) == 0x10);
        CHECK(p.substr(2, 6) == std::string("\0\4MQTT", 6));
        CHECK(uint8_t(p[8]) == 4);
        CHECK(uint8_t(p[9]) == 0xC2);
        CHECK(uint8_t(p[10]) == 0);
        CHECK(uint8_t(p[11]) == 60);
        BambuMqtt::Packet packet;
        REQUIRE(BambuMqtt::parse_packet(p, packet) == p.size());
        CHECK(packet.type == BambuMqtt::CONNECT);
    }
    SECTION("publish round trip with a long payload") {
        const std::string payload(300, 'x');
        const std::string p = BambuMqtt::publish_packet("device/01P00A123/request", payload);
        // 2 + 24 + 300 = 326 bytes: two length bytes.
        CHECK(uint8_t(p[1]) == (326 % 128 | 0x80));
        CHECK(uint8_t(p[2]) == 326 / 128);
        BambuMqtt::Packet packet;
        CHECK(BambuMqtt::parse_packet(p.substr(0, 10), packet) == 0);
        REQUIRE(BambuMqtt::parse_packet(p + "trailing", packet) == p.size());
        std::string topic, body;
        REQUIRE(BambuMqtt::parse_publish(packet, topic, body));
        CHECK(topic == "device/01P00A123/request");
        CHECK(body == payload);
    }
    SECTION("QoS 1 publish has a packet id") {
        std::string body;
        body += char(0); body += char(5); body += "a/b/c"; body += char(0); body += char(7); body += "{}";
        BambuMqtt::Packet packet{ BambuMqtt::PUBLISH, 0x02, body };
        std::string topic, payload;
        REQUIRE(BambuMqtt::parse_publish(packet, topic, payload));
        CHECK(topic == "a/b/c");
        CHECK(payload == "{}");
    }
    SECTION("subscribe") {
        const std::string p = BambuMqtt::subscribe_packet(1, "device/X/report");
        CHECK(uint8_t(p[0]) == 0x82);
        CHECK(p.back() == '\0');
    }
}

TEST_CASE("Bambu status report", "[BambuLan]")
{
    BambuStatus status;
    CHECK(!status.update_from_report(R"({"info":{}})"));
    CHECK(!status.update_from_report("not json"));
    REQUIRE(status.update_from_report(R"({"print":{"gcode_state":"RUNNING","mc_percent":42,"mc_remaining_time":17,"nozzle_temper":219.6,"bed_temper":55}})"));
    CHECK(status.gcode_state == "RUNNING");
    CHECK(status.percent == 42);
    CHECK(status.remaining_min == 17);
    CHECK(status.nozzle_temp > 219.);
    // P1 printers only send what changed: the other fields stay.
    REQUIRE(status.update_from_report(R"({"print":{"mc_percent":43}})"));
    CHECK(status.percent == 43);
    CHECK(status.gcode_state == "RUNNING");
}

TEST_CASE("Bambu job file", "[BambuLan]")
{
    const fs::path dir = fs::temp_directory_path() / fs::unique_path("tisma-bambu-test-%%%%");
    fs::create_directories(dir);
    const fs::path gcode = dir / "part.gcode";
    {
        std::ofstream out(gcode.string(), std::ios::binary);
        out << "; generated by Tisma\nG28\nG1 X10 Y10 E1\n";
    }
    // MD5 of the text above, computed with md5sum.
    CHECK(file_md5_upper_hex(gcode) == "3715646477F4F5417CE4136E4949697F");

    const fs::path job = dir / "part.gcode.3mf";
    std::string error;
    REQUIRE(write_bambu_gcode_3mf(gcode, job, error));

    mz_zip_archive archive;
    mz_zip_zero_struct(&archive);
    REQUIRE(open_zip_reader(&archive, job.string()));
    auto read = [&archive](const char *name) {
        size_t size = 0;
        void *data = mz_zip_reader_extract_file_to_heap(&archive, name, &size, 0);
        std::string s = data ? std::string(static_cast<char *>(data), size) : std::string();
        mz_free(data);
        return s;
    };
    CHECK(read("Metadata/plate_1.gcode") == "; generated by Tisma\nG28\nG1 X10 Y10 E1\n");
    CHECK(read("Metadata/plate_1.gcode.md5") == file_md5_upper_hex(gcode));
    CHECK(read("[Content_Types].xml").find("text/x.gcode") != std::string::npos);
    CHECK(!read("3D/3dmodel.model").empty());
    close_zip_reader(&archive);
    fs::remove_all(dir);
}

TEST_CASE("Bambu start command", "[BambuLan]")
{
    const nlohmann::json j = nlohmann::json::parse(bambu_project_file_command("part.gcode.3mf", true, 7));
    const auto &p = j.at("print");
    CHECK(p.at("command") == "project_file");
    CHECK(p.at("param") == "Metadata/plate_1.gcode");
    CHECK(p.at("url") == "ftp://part.gcode.3mf");
    CHECK(p.at("use_ams") == true);
    CHECK(p.at("sequence_id") == "7");
}

// End to end against tools/bambu/fake_printer.py (TLS with a test CA, MQTT and implicit FTPS):
//   python3 tools/bambu/fake_printer.py --dir /tmp/fake &   then
//   TISMA_BAMBU_FAKE=/tmp/fake slic3rutils_tests "[BambuLanFake]"
TEST_CASE("Bambu LAN against the fake printer", "[.][BambuLanFake]")
{
    const char *dir = std::getenv("TISMA_BAMBU_FAKE");
    REQUIRE(dir != nullptr);
    BambuLanClient client;
    client.host        = "127.0.0.1";
    client.access_code = "12345678";
    client.cafile      = (fs::path(dir) / "ca.pem").string();
    client.mqtt_port   = 18883;
    client.ftps_port   = 18990;

    BambuStatus status;
    std::string error;
    REQUIRE(client.query_status(status, error, 5));
    CHECK(status.serial == "01P00A000000001");
    CHECK(status.gcode_state == "IDLE");

    SECTION("wrong access code") {
        BambuLanClient bad = client;
        bad.access_code = "00000000";
        BambuStatus s;
        CHECK(!bad.query_status(s, error, 5));
        CHECK(error == "access code");
        const fs::path f = fs::temp_directory_path() / "tisma_bad.txt";
        { std::ofstream(f.string()) << "x"; }
        CHECK(!bad.upload_file(f, "x.txt", {}, error));
        CHECK(error == "access code");
    }

    SECTION("certificate not issued by the CA") {
        BambuLanClient other = client;
        other.cafile = (fs::path(dir) / "server.pem").string() + ".missing";
        BambuStatus s;
        CHECK(!other.query_status(s, error, 5));
    }

    SECTION("upload and start") {
        const fs::path gcode = fs::temp_directory_path() / "tisma bambu.gcode";
        {
            std::ofstream out(gcode.string());
            for (int i = 0; i < 20000; ++i)
                out << "G1 X" << i % 200 << " Y10 E0.1\n";
        }
        size_t last_progress = 0;
        REQUIRE(client.print(gcode, "tisma bambu.gcode", true, false,
                             [&last_progress](size_t sent, size_t) { last_progress = sent; return true; }, error));
        CHECK(last_progress > 0);
        const fs::path uploaded = fs::path(dir) / "sdcard" / "tisma_bambu.gcode.3mf";
        REQUIRE(fs::exists(uploaded));
        CHECK(last_progress == fs::file_size(uploaded));
        // The fake printer stores the last command it got.
        std::ifstream in((fs::path(dir) / "last_command.json").string());
        const nlohmann::json cmd = nlohmann::json::parse(in);
        CHECK(cmd.at("print").at("command") == "project_file");
        CHECK(cmd.at("print").at("url") == "ftp://tisma_bambu.gcode.3mf");
        fs::remove(gcode);
    }

    SECTION("cancel the upload") {
        const fs::path gcode = fs::temp_directory_path() / "tisma_cancel.gcode";
        { std::ofstream out(gcode.string()); for (int i = 0; i < 200000; ++i) out << "G1 X" << i % 200 << " Y" << i % 97 << " E0.1\n"; }
        CHECK(!client.print(gcode, "tisma_cancel.gcode", false, false, [](size_t sent, size_t) { return sent == 0; }, error));
        CHECK(error == "cancelled");
        fs::remove(gcode);
    }
}
